<!-- Banner Start -->

<section class="banner position-relative">

    <div class="parallax" style="background-image: url(assets/images/banner.webp);"></div>

    <div class="banner-data text-center">

        <h2 class="text-white font-bold">Events</h2>

        <ul class="flex-all">

            <li><a href="JavaScript:void(0)" class="text-white">Home</a></li>

            <li><a href="JavaScript:void(0)" class="text-white">Events</a></li>

        </ul>

         

    </div>

</section>

<!-- Banner End -->



<!-- Contact Us Start -->

<section class="gap events">

    <div class="container">

        <div class="row">

            <div class="col-lg-4 col-md-6 col-sm-12">

                <div class="event">

                    <img src="assets/images/event-img-3.webp" alt="Event Image 1">

                    <div class="event-data">

                        <p class="text-white">Stom Park New York</p>

                        <h4><a href="?page=event-detail" tabindex="0">Suicide Loss Grief Support Group</a></h4>

                        <ul>

                            <li><img src="assets/images/calendar.svg" alt="calendar 1">Thursday, June 4, 2020</li>

                            <li><img src="assets/images/clock.svg" alt="clock 1">1:00 pm - 2:00 pm</li>

                        </ul>

                        <a class="theme-btn" href="JavaScript:void(0)" tabindex="0">Book Your Seat</a>

                    </div>

                </div>

            </div>

            <div class="col-lg-4 col-md-6 col-sm-12">

                <div class="event">

                    <img src="assets/images/event-img-1.webp" alt="Event Image 2">

                    <div class="event-data">

                        <p class="text-white">Stom Park New York</p>

                        <h4><a href="?page=event-detail" tabindex="0">Suicide Loss Grief Support Group</a></h4>

                        <ul>

                            <li><img src="assets/images/calendar.svg" alt="calendar 2">Thursday, June 4, 2020</li>

                            <li><img src="assets/images/clock.svg" alt="clock 2">1:00 pm - 2:00 pm</li>

                        </ul>

                        <a class="theme-btn" href="JavaScript:void(0)" tabindex="0">Book Your Seat</a>

                    </div>

                </div>

            </div>

            <div class="col-lg-4 col-md-6 col-sm-12">

                <div class="event">

                    <img src="assets/images/event-img-3.webp" alt="Event Image 3">

                    <div class="event-data">

                        <p class="text-white">Stom Park New York</p>

                        <h4><a href="?page=event-detail" tabindex="0">Suicide Loss Grief Support Group</a></h4>

                        <ul>

                            <li><img src="assets/images/calendar.svg" alt="calendar 3">Thursday, June 4, 2020</li>

                            <li><img src="assets/images/clock.svg" alt="clock 3">1:00 pm - 2:00 pm</li>

                        </ul>

                        <a class="theme-btn" href="JavaScript:void(0)" tabindex="0">Book Your Seat</a>

                    </div>

                </div>

            </div>

            <div class="col-lg-4 col-md-6 col-sm-12">

                <div class="event">

                    <img src="assets/images/events-img-2.webp" alt="Event Image 4">

                    <div class="event-data">

                        <p class="text-white">Stom Park New York</p>

                        <h4><a href="?page=event-detail" tabindex="0">Suicide Loss Grief Support Group</a></h4>

                        <ul>

                            <li><img src="assets/images/calendar.svg" alt="calendar 4">Thursday, June 4, 2020</li>

                            <li><img src="assets/images/clock.svg" alt="clock 4">1:00 pm - 2:00 pm</li>

                        </ul>

                        <a class="theme-btn" href="JavaScript:void(0)" tabindex="0">Book Your Seat</a>

                    </div>

                </div>

            </div>

            <div class="col-lg-4 col-md-6 col-sm-12">

                <div class="event">

                    <img src="assets/images/events-img.webp" alt="Event Image 5">

                    <div class="event-data">

                        <p class="text-white">Stom Park New York</p>

                        <h4><a href="?page=event-detail" tabindex="0">Suicide Loss Grief Support Group</a></h4>

                        <ul>

                            <li><img src="assets/images/calendar.svg" alt="calendar 5">Thursday, June 4, 2020</li>

                            <li><img src="assets/images/clock.svg" alt="clock 5">1:00 pm - 2:00 pm</li>

                        </ul>

                        <a class="theme-btn" href="JavaScript:void(0)" tabindex="0">Book Your Seat</a>

                    </div>

                </div>

            </div>

            <div class="col-lg-4 col-md-6 col-sm-12">

                <div class="event">

                    <img src="assets/images/event-img-1.webp" alt="Event Image 6">

                    <div class="event-data">

                        <p class="text-white">Stom Park New York</p>

                        <h4><a href="?page=event-detail" tabindex="0">Suicide Loss Grief Support Group</a></h4>

                        <ul>

                            <li><img src="assets/images/calendar.svg" alt="calendar 6">Thursday, June 4, 2020</li>

                            <li><img src="assets/images/clock.svg" alt="clock 6">1:00 pm - 2:00 pm</li>

                        </ul>

                        <a class="theme-btn" href="JavaScript:void(0)" tabindex="0">Book Your Seat</a>

                    </div>

                </div>

            </div>

            <div class="col-lg-4 col-md-6 col-sm-12">

                <div class="event">

                    <img src="assets/images/events-img-2.webp" alt="Event Image 7">

                    <div class="event-data">

                        <p class="text-white">Stom Park New York</p>

                        <h4><a href="?page=event-detail" tabindex="0">Suicide Loss Grief Support Group</a></h4>

                        <ul>

                            <li><img src="assets/images/calendar.svg" alt="calendar 7">Thursday, June 4, 2020</li>

                            <li><img src="assets/images/clock.svg" alt="clock 7">1:00 pm - 2:00 pm</li>

                        </ul>

                        <a class="theme-btn" href="JavaScript:void(0)" tabindex="0">Book Your Seat</a>

                    </div>

                </div>

            </div>

            <div class="col-lg-4 col-md-6 col-sm-12">

                <div class="event">

                    <img src="assets/images/event-img-3.webp" alt="Event Image 8">

                    <div class="event-data">

                        <p class="text-white">Stom Park New York</p>

                        <h4><a href="?page=event-detail" tabindex="0">Suicide Loss Grief Support Group</a></h4>

                        <ul>

                            <li><img src="assets/images/calendar.svg" alt="calendar 8">Thursday, June 4, 2020</li>

                            <li><img src="assets/images/clock.svg" alt="clock 8">1:00 pm - 2:00 pm</li>

                        </ul>

                        <a class="theme-btn" href="JavaScript:void(0)" tabindex="0">Book Your Seat</a>

                    </div>

                </div>

            </div>

        </div>

        <div class="d-flex justify-content-center loadmore">

            <a href="JavaScript:void(0)" class="theme-btn">Load More</a>

        </div>

    </div>

</section>

<!-- Contact Us End -->



<!-- Subscribe Start -->

<section class="subscribe">

    <div class="container">

        <div class="row align-items-center">

            <div class="col-lg-5 col-md-12 col-sm-12">

                <h3 class="text-white">Let’s Keep in Touch!</h3>

                <p class="text-white">Subscribe to keep up with fresh news and exciting updates.</p>

            </div>

            <div class="col-lg-7 col-md-12 col-sm-12">

                <form>

                    <input type="text" name="Text" placeholder="Enter Your Email Address...">

                    <button>Subscribe</button>

                </form>

            </div>

        </div>

    </div>

</section>

<!-- Subscribe End -->