<!-- Banner Start -->

<section class="banner position-relative">

    <div class="parallax" style="background-image: url(assets/images/banner.webp);"></div>

    <div class="banner-data text-center">

        <h2 class="text-white font-bold">Blog</h2>

        <ul class="flex-all">

            <li><a href="JavaScript:void(0)" class="text-white">Home</a></li>

            <li><a href="JavaScript:void(0)" class="text-white">Blog</a></li>

        </ul>

         

    </div>

</section>

<!-- Banner End -->



<!-- Contact Us Start -->

<div class="gap our-blog">

    <div class="container">

        <div class="row">

            <div class="col-lg-4 col-md-6 col-sm-12">

                <div class="blog-meta aos-init aos-animate" data-aos="fade-up" data-aos-duration="700">

                    <figure>

                        <img class="img-fluid" src="assets/images/blog-img.webp" alt="Blog image">

                    </figure>

                    <ul>

                        <li class="date">21 Dec, 2021</li>

                        <li><img src="assets/images/message.svg" alt="Message">12</li>

                    </ul>

                    <a href="?page=blog-detail" class="font-bold">Public Health By Allowing California Order</a>

                    <p>Alienum phaedrum toquatoeu, vis detraxit iculis eiex petenis in mei Mei an peri sl gra an peri sl graecis vix apernihil.</p>

                </div>

            </div>

            <div class="col-lg-4 col-md-6 col-sm-12">

                <div class="blog-meta aos-init aos-animate" data-aos="fade-up" data-aos-duration="1000">

                    <figure>

                        <img class="img-fluid" src="assets/images/blog-img-2.webp" alt="Blog image 2">

                    </figure>

                    <ul>

                        <li class="date">21 Dec, 2021</li>

                        <li><img src="assets/images/message.svg" alt="Message 2">12</li>

                    </ul>

                    <a href="?page=blog-detail" class="font-bold">Public Health By Allowing California Order</a>

                    <p>Alienum phaedrum toquatoeu, vis detraxit iculis eiex petenis in mei Mei an peri sl gra an peri sl graecis vix apernihil.</p>

                </div>

            </div>

            <div class="col-lg-4 col-md-6 col-sm-12">

                <div class="blog-meta aos-init aos-animate" data-aos="fade-up" data-aos-duration="1300">

                    <figure>

                        <img class="img-fluid" src="assets/images/blog-img-3.webp" alt="Blog image 3">

                    </figure>

                    <ul>

                        <li class="date">21 Dec, 2021</li>

                        <li><img src="assets/images/message.svg" alt="Message 3">12</li>

                    </ul>

                    <a href="?page=blog-detail" class="font-bold">Public Health By Allowing California Order</a>

                    <p>Alienum phaedrum toquatoeu, vis detraxit iculis eiex petenis in mei Mei an peri sl gra an peri sl graecis vix apernihil.</p>

                </div>

            </div>

            <div class="col-lg-4 col-md-6 col-sm-12">

                <div class="blog-meta aos-init aos-animate" data-aos="fade-up" data-aos-duration="700">

                    <figure>

                        <img class="img-fluid" src="assets/images/blog-img-3.webp" alt="Blog image 4">

                    </figure>

                    <ul>

                        <li class="date">21 Dec, 2021</li>

                        <li><img src="assets/images/message.svg" alt="Message 4">12</li>

                    </ul>

                    <a href="?page=blog-detail" class="font-bold">Public Health By Allowing California Order</a>

                    <p>Alienum phaedrum toquatoeu, vis detraxit iculis eiex petenis in mei Mei an peri sl gra an peri sl graecis vix apernihil.</p>

                </div>

            </div>

            <div class="col-lg-4 col-md-6 col-sm-12">

                <div class="blog-meta aos-init aos-animate" data-aos="fade-up" data-aos-duration="1000">

                    <figure>

                        <img class="img-fluid" src="assets/images/blog-img-2.webp" alt="Blog image 5">

                    </figure>

                    <ul>

                        <li class="date">21 Dec, 2021</li>

                        <li><img src="assets/images/message.svg" alt="Message 5">12</li>

                    </ul>

                    <a href="?page=blog-detail" class="font-bold">Public Health By Allowing California Order</a>

                    <p>Alienum phaedrum toquatoeu, vis detraxit iculis eiex petenis in mei Mei an peri sl gra an peri sl graecis vix apernihil.</p>

                </div>

            </div>

            <div class="col-lg-4 col-md-6 col-sm-12">

                <div class="blog-meta aos-init aos-animate" data-aos="fade-up" data-aos-duration="1300">

                    <figure>

                        <img class="img-fluid" src="assets/images/blog-img.webp" alt="Blog image 6">

                    </figure>

                    <ul>

                        <li class="date">21 Dec, 2021</li>

                        <li><img src="assets/images/message.svg" alt="Message 6">12</li>

                    </ul>

                    <a href="?page=blog-detail" class="font-bold">Public Health By Allowing California Order</a>

                    <p>Alienum phaedrum toquatoeu, vis detraxit iculis eiex petenis in mei Mei an peri sl gra an peri sl graecis vix apernihil.</p>

                </div>

            </div>

        </div>

        <div class="d-flex justify-content-center loadmore">

            <a href="JavaScript:void(0)" class="theme-btn">Load More</a>

        </div>

    </div>

</div>

<!-- Contact Us End -->